### PR TITLE
__file__ usage in CommonFilters

### PR DESCRIPTION
**Pull request by fireclawthefox**
Removed __file__ usage due to unavailability in deploy-ng builds
Moved Cg filters from sha files into separate python scripts
Removed now obsolete loadShader function from CommonFilters

### CODE REVIEW

**Comment by rdb** [comment]
Thanks!

**Comment by wezu** [comment]
If loadShader got removed then the snake case alias "load_shader=loadShader" should now also be removed

**Comment by fireclawthefox** [comment]
@wezu the load_shader=loadShader alias is as far as I can see only given in the Loader.py script which doesn't correspond with the removed loadShader from the CommonFilters but instead uses the loadShader from the ShaderPool which is implemented on the C++ side.

**Comment by wezu** [comment]
I think I've added in in CommonFilters.py back when in had a loadShader function, and I see it here now: https://github.com/panda3d/panda3d/blob/deploy-ng/direct/src/filter/CommonFilters.py#L556

**Comment by fireclawthefox** [comment]
ah, yes you're right, that should probably be removed then.

**Comment by rdb** [comment]
Fixed the `loadShader` issue in 624f28f.

**Pull request merged**
