### PR TITLE
Separating strings from blobs in dcparser

### PR DESCRIPTION
**Pull request by rdb**
This is a suggestion for how to solve the Python 3 compatibility issues in dcparser.  It already makes a distinction between text strings and binary blobs, so this change changes it so that `vector_uchar` is used for decoding and encoding blob data.

It also uses `vector_uchar` for representing any packed data.  A separate `get_bytes()` is added to DCPacker since the existing `get_string()` isn't really named accurately any more.

@cfsworks I've marked you as reviewer because you're in a better position than I am at checking whether this is going to break anything, or whether this it is at all a good idea to treat strings as UTF-8 in dcparser.

### CODE REVIEW

**Comment by CFSworks** [comment]
@rdb Thanks! I'll review it when I'm not on mobile.

I've been thinking about this a lot myself and like the idea of making string officially a UTF8 type. This would mean some changes to Astron which currently assumes (I believe) Latin1, but UTF8 is much better.

One thought I'm grappling with, however, is how to treat range constraints on the string type. UTF8 breaks the assumption that the string length equals the data length (except for ASCII strings). On one hand, at the high level, users except those length constraints to apply to the actual value being sent. But on the other, low level users will need a mechanism to provide explicit size limits.

The former is more consistent with the other length constraints, but the latter is faster to check. Although, network intermediaries (e.g. Astron's CA) should verify well-formed UTF8 from any malicious source anyway, so maybe we should go that route and just tell people "maximum size is 4 times maximum length"?

**Comment by rdb** [comment]
Theoretically we could distinguish latin-1 strings from UTF-8 strings, but I would prefer to just keep things simple and say that all strings everywhere in Panda are UTF-8.  I also think we should get rid of the use of wide strings in Panda3D except for communicating with the Win32 API.

So far, everywhere we're using the notion of 'size' and 'length' of strings (which are annoyingly the exact same thing in the C++ string class), it is referring to the number of code units, not code points, since most code that processes strings is completely oblivious of the encoding and just cares about the number of bytes in memory.  Similarly, it would be easiest for networking code not to have to parse the strings in order to process them.

What exactly is the aim of the range constraints you refer to?

**Comment by CFSworks** [comment]
> What exactly is the aim of the range constraints you refer to?

The .dc syntax allows writing constructs like `setName(string(1-64) name)`.
When `string` was assumed to be ASCII, this would set both the length (in characters) and size (in bytes) limits for "name" - the DC system would then perform constraints checking on any received or to-be-sent message to ensure that constraint is respected. It's useful both as a debugging aid as well as a countermeasure against maliciously crafted input. For example, nobody can set a blank name (due to requiring a minimum length of 1) and nobody can overflow the handling code (due to having a maximum size of 64).

Decoupling length and size by switching to UTF8 means we need to decide which one the range syntax applies to - they both have their uses, but I'm thinking "length" (as in number of codepoints) is the more consistent with what a game programmer would expect (they tend not to care about the bytes on the wire), and with the other range constraints (e.g. in arrays it applies to the number of array elements).

I'm not in favor of Latin1, by the way. Just commenting that I'll need to make the same change to the Astron codebase once this change lands here.

**Comment by rdb** [comment]
Ah, thank you for the explanation.  Then yes, number of code points makes the most sense here, since that's independent of the exact encoding.  People will expect the length restrictions to be consistent with the Python-reported `len()`, as well.

The only case where I thought people might expect it to be the number of code units (ie. bytes) is if this constraint is imposed based on a hard database or storage limitation, eg. if they need it to fit in a 64 byte field, but it seems that databases like MySQL actually measure string size constraints in number of codepoints too, even for UTF-8.

An optimized, quick range checker could entirely skip the range validation if `num_code_units <= limit`, and can early-reject the string if `num_code_units > limit * 4`, but I suppose it may be desirable to add additional validation that the string is indeed valid UTF-8 to catch encoding errors early.

**Comment by abtechmg** [comment]
How would i go about adding this to the latest development build? I finally after hours of installing and uninstalling found out how to compile source without issue, i however attempted adding this but obviously did something wrong. I'm not pro at C++ so i have no clue what i'm doing to be honest.

**Comment by drewc5131** [comment]
### praise the lord finally

**Comment by rdb** [comment]
@abtechmg I just rebased the branch onto the latest master, so you should be able to just check out or merge the `dcparser-bytes` branch without issues now.

I'll leave it up to @CFSworks to merge this at his discretion since he may need to coordinate it with changes to Astron.

**Comment by rdb** [comment]
@cfsworks Do you have time to look into this one within the next 10 days?  I'd like this to be in 1.10.

**Comment by rdb** [comment]
@CFSworks It'd suffice to do a quick smoke test to ensure this at least doesn't break existing Python 2 applications.

**Comment by CFSworks** [comment]
@rdb I just did a fairly heavy tire-kicking with this. It doesn't break Python 2. Is that enough to cherry-pick for 1.10?

**Comment by rdb** [comment]
@CFSworks Perfect, thanks a ton!

**Pull request closed without merging**
