### PR TITLE
Bring Recast/Detour integration into working order.

### PR DESCRIPTION
**Pull request by Maxwell175**
## Issue description

This PR will massively cleanup the Recast/Detour integration and bring it into working order as of current master.

## Solution description

This PR will fix the merge issues from moving up to latest master, overhaul the code to work reliably, bring the code into conformance with Panda3D standards, improve commenting.

## Checklist
I have done my best to ensure that…
* [x] …I have familiarized myself with the CONTRIBUTING.md file
* [x] …this change follows the coding style and design patterns of the codebase
* [x] …I own the intellectual property rights to this code
* [x] …the intent of this change is clearly explained
* [ ] …existing uses of the Panda3D API are not broken
* [ ] …the changed code is adequately covered by the test suite, where possible.

### CODE REVIEW

**Comment by Maxwell175** [comment]
Current personal TODO list:

* [ ] Implement generating navmesh from bullet shapes.
* [ ] Figure out and implement use of nav mesh tiles for quickly adding dynamic elements to a nevmesh.

**Comment by janEntikan** [comment]
Getting this merged would be pretty rad.

**Comment by Maxwell175** [comment]
Added Nav Mesh Obstacles (Currently only cylinder, but other types like boxes are possible). This allows to have a large number of moving obstacles on the same navmesh.

**Comment by Moguri** [comment]
Where are we at with this? I think adding additional obstacle types could always be added later if need be. However, fixing BAM writing and the broken build config would need to be done prior to a merge. Anything else?

**Comment by Moguri** [comment]
Any updates? Do you think you'll be able to get to the remaining todo items in the next few months?

**Comment by Maxwell175** [comment]
Rebased on to master. Work will continue in #1606.

**Pull request closed without merging**
