### PR TITLE
remove extensions folder

### PR DESCRIPTION
**Pull request by mgracer48**

### CODE REVIEW

**Comment by mgracer48** [comment]
according to @rdb this is deprecated so i removed the folder :)

**Comment by mgracer48** [comment]
when you deprecated  this i wonder why you guys forgot to delete this folder?

**Comment by mgracer48** [comment]
and what about extensions_native is that deprecated too?

**Comment by rdb** [comment]
The extensions folder was replaced by extensions_native.  I think it was left around at the time for people who still relied on the old method of building the Panda bindings, but nobody has done that in many years now.

extensions_native is still in use today.  Ideally, we'd like to phase it out, by moving the relevant code into C++ instead.

**Comment by mgracer48** [comment]
another question, did you work for disney?

**Pull request merged**
