### PR TITLE
Add sample showing some Panda3D uses of libRocket.

### PR DESCRIPTION
**Pull request by eswartz**
N.B.  This still uses the "from _rocketcore import rocket" hack.  

I noticed that 3rd-party Rocket files tend to have embedded Python in &lt;script&gt;> elements in *.rml, which expects "import rocket" to work.  And that doesn't work at all in Panda3D now, as we discussed, so both Panda3D *.py and *.rml files need the same hack.  

Thus, whatever fixes are made should probably include ensuring "import rocket" will work whether or not Panda3D's rocket module is loaded.

### CODE REVIEW

**Comment by eswartz** [comment]
broken rendering on Windows -- working on it.

**Comment by eswartz** [comment]
Should work now.  Building/testing on OS X and that should take a while.

**Comment by eswartz** [comment]
OK, rebased agianst the model-path lookups.  Thanks!

**Comment by rdb** [comment]
Oops; in my mind I'd already merged this, but evidently not. Thanks again for contributing this sample!

**Pull request merged**
