### PR TITLE
Rename config_FOO.{h,cxx} to match library name

### PR DESCRIPTION
**Pull request by CFSworks**
Rationale:
- It's consistent with everything else in the codebase (except audiotraits, which is a bunch of libraries in one so it's kind of an exception anyway)
- I'd like this for the CMake branch: For autogenerating metalib main files in the build system, the `config_pstatclient.h` include should match the `init_libpstatclient()` init call.
- This is a good small-scale test of how well various Git clients handle file renames these days.

Caveats:
- There's some renaming going on here.
- The renaming is also changing a couple of lines in the file in one commit. Because Git just uses a "file similarity" algorithm to detect renames (rather than recording the file change explicitly in the commit object), this _could_ upset buggy/older versions of Git.
- Everybody should check this branch to make sure their Git client is preserving file (not path) history for the files that have changed.

### CODE REVIEW

**Comment by keithbriantomo** [comment]
http://www.mlmrecruitondemand.com/freevideo.php?id=jesrelgarcia21

On Thursday, May 10, 2018, Sam Edwards <notifications@github.com> wrote:
> Rationale:
>
> It's consistent with everything else in the codebase (except audiotraits,
which is a bunch of libraries in one so it's kind of an exception anyway)
> I'd like this for the CMake branch: For autogenerating metalib main files
in the build system, the config_pstatclient.h include should match the
init_libpstatclient() init call.
> This is a good small-scale test of how well various Git clients handle
file renames these days.
>
> Caveats:
>
> There's some renaming going on here.
> The renaming is also changing a couple of lines in the file in one
commit. Because Git just uses a "file similarity" algorithm to detect
renames (rather than recording the file change explicitly in the commit
object), this could upset buggy/older versions of Git.
> Everybody should check this branch to make sure their Git client is
preserving file (not path) history for the files that have changed.
>
> ________________________________
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/panda3d/panda3d/pull/316
>
> Commit Summary
>
> pstatclient: Rename config_pstats to config_pstatclient
> putil: Rename config_util to config_putil
> pfmprogs: Rename config_pfm to config_pfmprogs
>
> File Changes
>
> M makepanda/makepanda.py (4)
> M makepanda/makepanda.vcproj (8)
> M panda/metalibs/panda/panda.cxx (2)
> M panda/src/android/android_main.cxx (2)
> M panda/src/audio/audioManager.cxx (2)
> M panda/src/audiotraits/fmodAudioManager.cxx (2)
> M panda/src/audiotraits/milesAudioManager.cxx (2)
> M panda/src/audiotraits/openalAudioManager.cxx (2)
> M panda/src/collada/load_collada_file.cxx (2)
> M panda/src/display/graphicsPipeSelection.cxx (2)
> M panda/src/display/graphicsStateGuardian.cxx (2)
> M panda/src/display/pStatGPUTimer.h (2)
> M panda/src/egg/eggData.cxx (2)
> M panda/src/egg2pg/load_egg_file.cxx (2)
> M panda/src/egg2pg/save_egg_file.cxx (2)
> M panda/src/glstuff/glGraphicsStateGuardian_src.cxx (2)
> M panda/src/gobj/config_gobj.cxx (2)
> M panda/src/gobj/shader.cxx (2)
> M panda/src/gobj/texture.cxx (2)
> M panda/src/gobj/texturePool.cxx (2)
> M panda/src/iphonedisplay/iPhoneGraphicsWindow.mm (2)
> M panda/src/movies/movieTypeRegistry.cxx (2)
> M panda/src/osxdisplay/osxGraphicsWindow.mm (2)
> M panda/src/pgraph/bamFile.cxx (2)
> M panda/src/pgraph/loader.cxx (2)
> M panda/src/pgraph/shaderPool.cxx (2)
> M panda/src/physx/physxEnums.cxx (2)
> M panda/src/pnmtext/freetypeFont.cxx (2)
> R panda/src/pstatclient/config_pstatclient.cxx (8)
> R panda/src/pstatclient/config_pstatclient.h (4)
> M panda/src/pstatclient/p3pstatclient_composite1.cxx (2)
> M panda/src/pstatclient/pStatClient.cxx (2)
> M panda/src/pstatclient/pStatClientControlMessage.cxx (2)
> M panda/src/pstatclient/pStatClientImpl.cxx (2)
> M panda/src/pstatclient/pStatFrameData.cxx (2)
> M panda/src/pstatclient/pStatProperties.cxx (2)
> M panda/src/pstatclient/pStatServerControlMessage.cxx (2)
> M panda/src/pstatclient/test_client.cxx (2)
> M panda/src/putil/autoTextureScale.cxx (2)
> M panda/src/putil/bamCache.cxx (2)
> M panda/src/putil/bamCacheIndex.cxx (2)
> M panda/src/putil/bamCacheRecord.cxx (2)
> M panda/src/putil/bamEnums.cxx (2)
> M panda/src/putil/bamReader.cxx (2)
> M panda/src/putil/bamReader_ext.cxx (2)
> M panda/src/putil/bamWriter.cxx (2)
> M panda/src/putil/buttonRegistry.cxx (2)
> M panda/src/putil/clockObject.cxx (2)
> M panda/src/putil/colorSpace.cxx (2)
> R panda/src/putil/config_putil.N (0)
> R panda/src/putil/config_putil.cxx (8)
> R panda/src/putil/config_putil.h (4)
> M panda/src/putil/copyOnWritePointer.cxx (2)
> M panda/src/putil/datagramInputFile.cxx (2)
> M panda/src/putil/datagramOutputFile.h (2)
> M panda/src/putil/factoryBase.cxx (2)
> M panda/src/putil/globalPointerRegistry.cxx (2)
> M panda/src/putil/keyboardButton.cxx (2)
> M panda/src/putil/load_prc_file.cxx (2)
> M panda/src/putil/loaderOptions.cxx (4)
> M panda/src/putil/mouseButton.cxx (2)
> M panda/src/putil/p3putil_composite1.cxx (2)
> M panda/src/putil/pythonCallbackObject.cxx (2)
> M panda/src/putil/simpleHashMap.h (2)
> M panda/src/putil/test_filename.cxx (2)
> M panda/src/putil/weakKeyHashMap.h (2)
> M panda/src/speedtree/speedTreeNode.cxx (2)
> M panda/src/text/dynamicTextFont.cxx (2)
> M panda/src/text/fontPool.cxx (2)
> M panda/src/tinydisplay/tinyOsxGraphicsWindow.mm (2)
> M panda/src/windisplay/winGraphicsWindow.cxx (2)
> M pandatool/src/bam/eggToBam.cxx (2)
> M pandatool/src/bam/ptsToBam.cxx (2)
> M pandatool/src/converter/somethingToEggConverter.h (2)
> M pandatool/src/egg-palettize/txaFileFilter.cxx (2)
> M pandatool/src/eggbase/eggReader.cxx (2)
> M pandatool/src/eggbase/somethingToEgg.cxx (2)
> M pandatool/src/flt/fltTexture.cxx (2)
> M pandatool/src/gtk-stats/gtkStats.cxx (2)
> M pandatool/src/maxegg/maxToEggConverter.cxx (2)
> M pandatool/src/mayaprogs/mayaPview.cxx (2)
> M pandatool/src/pandatoolbase/pathReplace.cxx (2)
> R pandatool/src/pfmprogs/config_pfmprogs.cxx (8)
> R pandatool/src/pfmprogs/config_pfmprogs.h (2)
> M pandatool/src/pfmprogs/pfmBba.cxx (2)
> M pandatool/src/pfmprogs/pfmTrans.cxx (2)
> M pandatool/src/pstatserver/pStatGraph.cxx (2)
> M pandatool/src/pstatserver/pStatPianoRoll.cxx (2)
> M pandatool/src/pstatserver/pStatServer.cxx (2)
> M pandatool/src/pstatserver/pStatStripChart.cxx (2)
> M pandatool/src/pstatserver/pStatThreadData.cxx (2)
> M pandatool/src/ptloader/loaderFileTypePandatool.cxx (2)
> M pandatool/src/text-stats/textStats.cxx (2)
> M pandatool/src/win-stats/winStats.cxx (2)
>
> Patch Links:
>
> https://github.com/panda3d/panda3d/pull/316.patch
> https://github.com/panda3d/panda3d/pull/316.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/yn0Ck1qLP6OhTNgQpcEFSWJskhTVwKetUNTZ1IKpbXoV4xsVzJ53DWxzv5Z3C_Qkr6ky7N2J2iT3XBLwunnpEyGzDua5bS8GYUpIF_2YsRYnNs18Xcnj8PGFSVnwEOlYt6JrtROys5_T8T2JDEshy4uaQ7YcKg=s0-d-e1-ft#https://github.com/notifications/beacon/AHN8yM1_JzECwwIXA0KFa2TxUbUODkuRks5tw2gAgaJpZM4T5ETZ.gif>

**Comment by rdb** [comment]
Should we leave in `config_util.h` etc. temporarily, as a simple include-forwarder, in order not to break API compatibility for C++ modules?  We could use some preprocessor pragma to issue a deprecation warning.

**Comment by CFSworks** [comment]
I could possibly see that for `config_util.h` and _maybe_ `config_pstats.h` (I doubt it's justified in the case of pfm).

However, if we're just going to remove that shim later on down the road, and it's a shim that works around only a very easy problem already, I don't see it doing much good. In cases where there's a more complex migration path (e.g. a function is deprecated and a slightly different function is introduced to provide similar functionality), I usually push for a compatibility layer with a deprecation notice, allowing upgrading users to adapt to the change at a later time when they have the headroom to focus on such a thing... But since downstream users can adjust to this with a basic `sed -i 's/config_util.h/config_putil.h/' $(grep -lR config_util)` - combined with the infrequency of third-party projects using that header directly to begin with - I don't so much see this as buying time for our users and moreso feel that it would just prolong the inevitable.

A header that contains `#error Please include config_putil.h instead of config_util.h` might make more sense if we really want something that'll make it clear to our users why `config_util.h` is suddenly missing - but with this kind of trivial change we might want it to be a build-stopping error as opposed to an ignorable warning.

But if you're still pushing for a warning, I'd be happy to add it. Thoughts?

**Comment by rdb** [comment]
Looks like the Travis job is failing; we may need to explicitly exclude these headers from being interrogated, using something like:
```python
  IGATEFILES.remove("config_util.h")
```

**Comment by CFSworks** [comment]
Thanks, that seemed to take care of it!

Since there were no further objections and this has been pending for a few days, I'm going to drop it in.

**Pull request merged**
