### PR TITLE
Orientation Fixes for Slider and Scrollbar

### PR DESCRIPTION
**Pull request by fireclawthefox**
Fixed sizing after orientation change
Added missing orientation change logic for the slider

### CODE REVIEW

**Comment by rdb** [comment]
Hmm, what if the user has specified a custom frame size?  Would this not then reset that custom size to the default?

**Comment by fireclawthefox** [comment]
Ah, yes that's true indeed. Maybe swapping the frameSize bits instead of overwriting them could work if we know the previous orientation. Will take a look into this later.

**Comment by rdb** [comment]
Swapping probably makes sense.

**Comment by rdb** [comment]
It looks like this might be ready to go, do you intend to add a unit test?

**Comment by fireclawthefox** [comment]
Do you think this simple unittest will be sufficient or should it be extended some more?

**Pull request closed without merging**
