### PR TITLE
do not prefer framebuffer configs with excessive multisamples

### LINKED ISSUE #1455: config variable multisamples not considered
## Description
When requesting a specific number of multisamples the window will get a display with the maximum number of multisamples possible.

## Steps to Reproduce
Add the following lines to the Config.prc file:

`framebuffer-multisample true`
`multisamples 4`
on GPUs with 16 max. 16 multisamples, the command

`window->get_graphics_output()->get_fb_properties().get_multisamples()`

will return 16 and not the requested 4.

## Environment
 * Operating system: Windows
 * System architecture: 64bit
 * Panda3D version: 1.11.0
 * Installation method: built from source
 * Python version (if using Python):
 * Compiler (if using C++): MSVC 14.3

### PR DESCRIPTION
**Pull request by git2323**
…more samples than requested

## Issue description
Related issue: #1455 
The change enhances the possibility to get a window with a requested number of multisamples.

## Solution description
there is a system to assign a quality level to a available display. Currently more multisamples get a higher quality.
This has been changed to give a higher quality level to a display which closer matches the requested one.

## Checklist
I have done my best to ensure that…
* [ x] …I have familiarized myself with the CONTRIBUTING.md file
* [ x] …this change follows the coding style and design patterns of the codebase
* [ x] …I own the intellectual property rights to this code
* [ x] …the intent of this change is clearly explained
* [ x] …existing uses of the Panda3D API are not broken
* [ x] …the changed code is adequately covered by the test suite, where possible.

Fixes #1455

### CODE REVIEW

**Comment by git2323** [comment]
Fixes #1455

**Review by rdb — CHANGES_REQUESTED** [review]
Good, thanks, but should apply the same logic to coverage samples then

**Review by rdb — DISMISSED** [review]
LGTM :+1:

**Comment by rdb** [comment]
Hang on, currently, if you request 4 samples but get 8, you still get 8 * 2 points deducted, was it intended to punish only for the excess samples?

**Comment by git2323** [comment]
> Hang on, currently, if you request 4 samples but get 8, you still get 8 * 2 points deducted, was it intended to punish only for the excess samples?

You get punished as to how far away you are from the request, so when you have 16 you get deducted 2 * 16 quality points because this config would be worse than 2 * 8 quality points in case of 8 samples.

**Review by rdb — CHANGES_REQUESTED** [review]
Please include ms=0 req/fb  sets in your tests.

**Review by rdb — APPROVED** [review]

**Pull request merged**
