### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jakemcf22**
## Issue Description
The usage of thirdparty vs third-party is inconsistent throughout the readme.
## Solution
Modified third-party vs thirdparty so that the usage in the paragraph is consistent with the links provided in the same paragraph.

### CODE REVIEW

**Review by Moguri — APPROVED** [review]
Looks good to me

**Review by Moguri — CHANGES_REQUESTED** [review]
Actually, on second thought, I believe we should prefer "third-party"

**Comment by rdb** [comment]
Ah, well, too late `¯\_(ツ)_/¯`

I suggest leaving it like this, I think minor stylistic changes to readme files shouldn't be a priority

**Comment by Moguri** [comment]
Yeah, not something to worry about. 😁

**Pull request merged**
