### PR TITLE
EggLoader: correctly import collision surfaces with non-global axes

### PR DESCRIPTION
**Pull request by PointSource-xx**
When creating solids from egg collision group, convert all vertices into local space before calculating the collision solids, otherwise solids with non-global axes and other transforms will be imported incorrectly. Fixes panda3d/panda3d#506

### CODE REVIEW

**Comment by rdb** [comment]
Looks like your change broke the double-precision build.  You probably should use `LCAST(PN_stdfloat, ...)` instead of `cast_to_float(...)`.

**Comment by PointSource-xx** [comment]
Changes made, checks now passing.

**Comment by PointSource-xx** [comment]
left an errant #include, oops.

**Comment by rdb** [comment]
Upon looking further at this, I'm actually not a big fan of transforming the entire group back and forth, and then leaving a transform on the resulting node.  I've checked in a fix based on your original patch in 4f94b3aa0ed9535d51e4112294c4927f300576ac (using a hack to make it work in 1.10 without breaking the ABI; I'll remove the hack when it lands on master).

**Pull request closed without merging**
