### PR TITLE
drag & drop

### PR DESCRIPTION
**Pull request by BMaxV**
This is a drag & drop system built with the directGUI, that I believe should be supported by panda out of the box in some way or another.

I adapted the script provided by wezu in this comment to do it:

https://github.com/panda3d/panda3d/issues/317#issuecomment-388323154

and it's part of the discussion in the same issue:

https://github.com/panda3d/panda3d/issues/317

### CODE REVIEW

**Comment by rdb** [comment]
@drewc5131 I agree that DirectGUI is not a great GUI system in many respects, but this is not the right thread to be having that discussion.  For what it's worth, though, [LUI](https://github.com/tobspr/LUI) is intended to be a better alternative.

**Comment by drewc5131** [comment]
@rdb Yeah I kinda just go off on rants without intending to haha, but yeah I have used LUI and it is nice, however theres some annoyances with it, mainly the fact that it doesnt scale like DGUI does with window scale.

**Comment by xordspar0** [comment]
I want to bring attention to this again. Do we _not_ want to merge this because DirectGUI should be replaced and we don't want to invest in it at all? Or should we merge this and then update it when DirectGUI changes?

**Comment by BMaxV** [comment]
It's a sample. While directGUI is in panda and while it is the more documented UI system, I'd say this is useful. I would have liked to have it.

If/When an alternative GUI system is included or merged and directGUI is replaced, I would like there to be feature parity and equally good or better documentation for the new system before directGUI is removed.

**Comment by xxxshelby** [comment]
How to change your files from 2D to 3D?

**Comment by xxxshelby** [comment]
How to change the file to C++?

**Comment by Moguri** [comment]
I am rebasing this branch so CI checks can run. This seems like something useful and it is simple to include (just a sample). However, we still need to review the code to make sure it is in line with our other samples.

I believe the fate of DirectGui is an orthogonal discussion -- especially without a clear successor -- and should not impact this PR.

**Review by rdb — CHANGES_REQUESTED** [review]
I think this needs more work in terms of code style, structure and readability to be useful as a sample.

**Pull request closed without merging**
