### PR TITLE
DirectOptionMenu bugfixes noted in: #637

### PR DESCRIPTION
**Pull request by fireclawthefox**
Fixes for #637
- Fix popupMarker_pos related crash
- Set initial popupMarker position to previous default by using None as default

### CODE REVIEW

**Comment by rdb** [comment]
Have you tested that this produces the correct (pre-1.10.3) behaviour both with and without the option set?

**Comment by fireclawthefox** [comment]
I haven't changed any of the placing behaviour and my tests showed me, that setting the popupMarker_pos to None will place it at the correct default position to the right, centered vertically. Which was AFAIK always the default. Setting it to (0,0,0) will put the marker to the lower left edge of the box as expected.
If that's what you're asking for.

**Comment by rdb** [comment]
Closed in 387b43adde75184ddb9801ee05188e0cc09da994

**Comment by tyteen4a03** [comment]
What's the workaround for this issue? Manually passing in a `popupMarker_pos` still causes p3d to crash the same way.

**Comment by ArsThaumaturgis** [comment]
Offhand, things that occur to me that should work: 
 - You can edit the code for DirectOptionMenu; a look at the patch that fixes the issue on GitHub should give you an idea of what to do. (It's a fairly simple fix, I seem to think.)
 - You can use a pre-release version of Panda
 - You can wait for the release of 1.10.4, which I think will have the fix.

**Pull request closed without merging**
