### PR TITLE
Change threads to 6 to build panda3d faster in Travis.yml

### PR DESCRIPTION
**Pull request by mgracer48**
Travis can handle this I did it with my own project

[Review on Reviewable](https://reviewable.io/reviews/panda3d/panda3d/63)

### CODE REVIEW

**Comment by rdb** [comment]
All Travis environments have two cores:
http://docs.travis-ci.com/user/ci-environment/
Increasing thread count to 6 will likely slow down the CI build.

**Comment by mgracer48** [comment]
Really because for my build I use 6 threads

**Comment by rdb** [comment]
Hmm, maybe this is useful after all.  The build with 6 threads did seem to be considerably faster.

**Comment by rdb** [comment]
Increased thread count to 4 on release/1.9.x branch, which seems almost just as fast as a 6-thread build.  Will be merged shortly.

**Pull request closed without merging**
