### PR TITLE
dcparser: export extension classes

### PR DESCRIPTION
**Pull request by lachbr**
Needed to access these classes in a separate .dll

### CODE REVIEW

**Comment by rdb** [comment]
Not sure how this is supposed to work, these aren't in libp3direct.dll, but in panda3d/core.pyd.

**Comment by lachbr** [comment]
Do you mean direct.pyd? I link with direct.lib.

**Comment by rdb** [comment]
That's not a supported way to do things, and in fact, we moved away from doing that entirely in the Panda source since 1.10 because of the amount of issues we ran into doing things like that (don't remember the exact reasons right now, but I can think of a couple potential ones).

Marking these EXPORT_CLASS wouldn't be the end of the world, but I'd like to consider whether there are other ways of doing this that would work with your use cases.  Using the Python C API to access these methods, for example.

**Comment by rdb** [comment]
Do you still need this change?

**Pull request closed without merging**
