### PR TITLE
Add issue tracker to readme :)

### PR DESCRIPTION
**Pull request by mgracer48**

### CODE REVIEW

**Comment by mgracer48** [comment]
@rdb why not merged?

**Comment by jdfreder** [comment]
> why not merged?

An attempt to mitigate the number of bugs ;)

**Comment by mgracer48** [comment]
? what

**Comment by mgracer48** [comment]
how would this make the bugs  "less severe, serious, or painful."

**Comment by tobspr** [comment]
@mgracer48 I'm pretty sure this wasn't in a serious way :D

**Comment by mgracer48** [comment]
now im confused

**Comment by rdb** [comment]
Updated README.md with bug tracker link.  I wanted to add in some extra information as well, and I've been sidetracked by numerous other things, which is why it took me a while to get to it.

**Pull request closed without merging**
