### PR TITLE
build_apps: Add hook for packages to modify options

### PR DESCRIPTION
**Pull request by Moguri**
## Issue description
Packages such as [panda3d-simplepbr](https://github.com/Moguri/panda3d-simplepbr/) require users to modify `build_apps` options to handle data files. It would be nice if such packages could automatically handle this for users.

## Solution description
This PR adds a 'panda3d.build_apps.modify_options' pkg_resources entry point. This allows packages to automatically handle setting/modifying any build_apps options.

## Checklist
I have done my best to ensure that…
* [x] …I have familiarized myself with the CONTRIBUTING.md file
* [x] …this change follows the coding style and design patterns of the codebase
* [x] …I own the intellectual property rights to this code
* [x] …the intent of this change is clearly explained
* [x] …existing uses of the Panda3D API are not broken
* [ ] …the changed code is adequately covered by the test suite, where possible.

### CODE REVIEW

**Review by rdb — COMMENTED** [review]
Could you show an example how a package will use this to modify options?

**Comment by Moguri** [comment]
I used this snippet in panda3d-simplepbr to test this with:

```python
def modify_options(build_apps_cmd):
    if 'simplepbr' not in build_apps_cmd.package_data_dirs:
        build_apps_cmd.package_data_dirs['simplepbr'] = [
            ('simplepbr/*.vert', '', {}),
            ('simplepbr/*.frag', '', {}),
        ]
```
And the following in `setup.py`:

```python
from setuptools import setup

setup(
    # ...
    entry_points={
        'panda3d.build_apps.modify_options': [
            'simplepbr=simplepbr.buildapps:modify_options'
        ]
    }
)
```

**Comment by Moguri** [comment]
@rdb is this something we'd like to continue to pursue? I no longer need this for simplepbr since it just bundles shaders into Python files. In other words, if we're on the fence on this, I'll probably just abandon this PR.

**Comment by Moguri** [comment]
This can actually be done with a `setuptools.finalize_distribution_options` entrypoint. Here is an example: https://github.com/Moguri/pman/blob/20b4ae113e57c6fb4bfb62b0d95c08997660f5aa/pman/setuptools.py

**Pull request closed without merging**
