### PR TITLE
config: Allow equal signs (=) between variable names and value

### PR DESCRIPTION
**Pull request by Moguri**
This allows for more INI-style syntax as proposed by #523. Sections are
still not supported.

### CODE REVIEW

**Comment by rdb** [comment]
Interesting.  I think this PR would allow `var = = value`, though?

I think the is_split_character, which is not declared externally, should be marked `static` (since it's not declared elsewhere, no point in giving it external linkage), and hoisted to the top of the .cxx file by Panda convention.

Do we want to enable this optionally, as part of a special mode for now (possibly toggled by extension), or do we want to allow this syntax for all .prc files?

**Comment by Moguri** [comment]
Yes, it allows any combination of spaces and equal signs. I figured this would be the simplest approach and PRC isn't very strict as is (e.g., anything start with "t" being "true").

I'll fix up the scope of is_split_character() and move it.

**Comment by Moguri** [comment]
I forced pushed a new version that only allows one equal sign.

**Comment by Moguri** [comment]
@rdb Is this PR something we want? What is missing to move this along? More discussion?

**Comment by rdb** [comment]
One question I raised for discussion remains unaddressed, and I'd like to carefully consider that before we make this otherwise irreversible change.

**Comment by Moguri** [comment]
I am going to abandon this PR for now and we can continue discussion in #523. I started this PR in the hopes of quickly getting an issue closed, but I am otherwise not strongly invested in the feature. The code will still be around for someone to pick up.

**Pull request closed without merging**
