### PR TITLE
bullet: fix wheel.getSteering() to return in degrees #757

### PR DESCRIPTION
**Pull request by leotada**
This should fix issue #757

### CODE REVIEW

**Comment by Moguri** [comment]
This looks good to me. What testing have you done? Some unit tests for this would be nice, but I don't think they are required to accept this PR.

**Comment by rdb** [comment]
Thanks, can you add unit tests?  I think unit tests should be a requirement for all PRs that change existing behaviours.

**Comment by leotada** [comment]
Ok, I will try to add the tests.

**Comment by leotada** [comment]
Is this ok?

**Comment by rdb** [comment]
getSteering() and setSteering() should use the same units.  Your unit test seems to indicate that setSteering takes a value in radians.  Could you fix setSteering to also use degrees?

**Comment by leotada** [comment]
Of course. The documentation don't mention the unit then I didn't know If I change.

**Comment by leotada** [comment]
@rdb please review! I can't resolve the change request status in Github.

**Pull request closed without merging**
