### PR TITLE
fix for bug 554, replace _signature by tp_flags for objects created by interrogate

### PR DESCRIPTION
**Pull request by JoelStienlet**

### CODE REVIEW

**Comment by rdb** [comment]
Were the changes to the readme and travis files intended to be included in this PR or did you push to the wrong branch?

**Comment by JoelStienlet** [comment]
Oh sorry! Just ignore / delete everything, I was trying to do some code coverage tests in my fork, but I clicked on the wrong buttons apparently.
I apologize for that noise.

**Comment by rdb** [comment]
Have you tested these changes?  The test suite immediately fails for me with:
```
=============================================================================================== ERRORS ================================================================================================
_________________________________________________________________________ ERROR collecting tests/display/test_color_buffer.py _________________________________________________________________________
tests/display/test_color_buffer.py:7: in <module>
    TEST_SCALED_COLOR.componentwise_mult(TEST_COLOR_SCALE)
E   TypeError: C++ object is not yet constructed, or already destructed.
__________________________________________________________________________ ERROR collecting tests/pgraph/test_lightattrib.py __________________________________________________________________________
tests/pgraph/test_lightattrib.py:4: in <module>
    spot = core.NodePath(core.Spotlight("spot"))
E   TypeError: Arguments must match:
E   NodePath()
E   NodePath(PandaNode node)
E   NodePath(str top_node_name)
E   NodePath(const NodePath copy)
E   NodePath(const NodePath parent, PandaNode child_node, Thread current_thread)
E   NodePath(PandaNode node, Thread current_thread)
E   NodePath(str top_node_name, Thread current_thread)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================================= 2 error in 0.71 seconds =======================================================================================
```

**Comment by JoelStienlet** [comment]
Hello rdb,
You may have missed my previous comment: this is an **error**, I was making changes in my fork, not intended to be pulled, and I don't know how they got here... I still don't understand. So, just ignore it, you can even delete all this. My apologies again for the disturbance.

For issue 581, I will submit a PR as soon as I finish reading "C++ concurrency in action" because I noticed that I was lacking some knowledge on the subject. It won't take long now, don't worry!

**Pull request closed without merging**
