### PR TITLE
bullet: replace NodePath scaling in BulletBodyNode::do_add_shape()

### LINKED ISSUE #689: Deadlock in `BulletBodyNode::add_shapes_from_collision_solids()`
```
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
#1  0x00007f2399e24945 in __GI___pthread_mutex_lock (mutex=0x7f2393c126e0 <BulletWorld::get_global_lock()::lock>) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f2393be4cd9 in MutexPosixImpl::lock() () from /usr/lib/x86_64-linux-gnu/panda3d/libpandabullet.so.1.10
#3  0x00007f2393bd2829 in BulletRigidBodyNode::transform_changed() [clone .part.1630] () from /usr/lib/x86_64-linux-gnu/panda3d/libpandabullet.so.1.10
#4  0x00007f2397d9acab in PandaNode::set_transform(TransformState const*, Thread*) () from /usr/lib/x86_64-linux-gnu/panda3d/libpanda.so.1.10
#5  0x00007f2397d13d80 in NodePath::set_scale(LVecBase3f const&) () from /usr/lib/x86_64-linux-gnu/panda3d/libpanda.so.1.10
#6  0x00007f2393bd07c5 in BulletBodyNode::do_add_shape(BulletShape*, TransformState const*) () from /usr/lib/x86_64-linux-gnu/panda3d/libpandabullet.so.1.10
#7  0x00007f2393bd1317 in BulletBodyNode::add_shapes_from_collision_solids(CollisionNode*) () from /usr/lib/x86_64-linux-gnu/panda3d/libpandabullet.so.1.10
#8  0x00007f2393c8d6ca in Dtool_BulletBodyNode_add_shapes_from_collision_solids_90(_object*, _object*) () from /usr/lib/python3/dist-packages/panda3d/bullet.cpython-37m-x86_64-linux-gnu.so
#9  0x00000000004d7d11 in _PyMethodDescr_FastCallKeywords ()
#10 0x0000000000552313 in _PyEval_EvalFrameDefault ()
#11 0x000000000054b9f2 in _PyEval_EvalCodeWithName ()
#12 0x00000000005d8c62 in _PyFunction_FastCallKeywords ()
#13 0x000000000054e3dc in _PyEval_EvalFrameDefault ()
#14 0x000000000054b9f2 in _PyEval_EvalCodeWithName ()
#15 0x00000000005d8c62 in _PyFunction_FastCallKeywords ()
#16 0x000000000054af20 in ?? ()
#17 0x000000000054f0ee in _PyEval_EvalFrameDefault ()
#18 0x00000000005d9ca6 in _PyFunction_FastCallDict ()
#19 0x0000000000591103 in ?? ()
#20 0x00000000005d93c9 in _PyObject_FastCallKeywords ()
#21 0x00000000005523b6 in _PyEval_EvalFrameDefault ()
#22 0x00000000005d896c in _PyFunction_FastCallKeywords ()
#23 0x000000000054e3dc in _PyEval_EvalFrameDefault ()
#24 0x00000000005d9ca6 in _PyFunction_FastCallDict ()
#25 0x0000000000591103 in ?? ()
#26 0x00000000005d93c9 in _PyObject_FastCallKeywords ()
#27 0x00000000005523b6 in _PyEval_EvalFrameDefault ()
#28 0x00000000005d9ca6 in _PyFunction_FastCallDict ()
#29 0x0000000000591103 in ?? ()
#30 0x00000000005d93c9 in _PyObject_FastCallKeywords ()
#31 0x00000000005523b6 in _PyEval_EvalFrameDefault ()
#32 0x000000000054b9f2 in _PyEval_EvalCodeWithName ()
#33 0x000000000054dd33 in PyEval_EvalCode ()
#34 0x0000000000630f22 in ?? ()
#35 0x0000000000630fd7 in PyRun_FileExFlags ()
#36 0x0000000000631c3f in PyRun_SimpleFileExFlags ()
#37 0x000000000065414e in ?? ()
#38 0x00000000006544ae in _Py_UnixMain ()
#39 0x00007f2399e60b6b in __libc_start_main (main=0x4bc950 <main>, argc=2, argv=0x7ffd68404af8, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7ffd68404ae8)
    at ../csu/libc-start.c:308
#40 0x00000000005e04ea in _start ()
```

### PR DESCRIPTION
**Pull request by PointSource-xx**
Use btCollisionShape::[get|set]LocalScaling() instead of scaling the NodePath when adding new shapes to avoid a circular deadlock on the BulletWorld global lock. Fixes #689.

### CODE REVIEW

**Comment by PointSource-xx** [comment]
> Please include unit tests that pass before and after this change.

Will do.

**Comment by PointSource-xx** [comment]
This program helps to visually display what's going on:
```python
import sys

from direct.showbase.DirectObject import DirectObject
from direct.showbase.InputStateGlobal import inputState

from panda3d.core import Vec2, Vec3, TransformState

from panda3d.bullet import BulletWorld, BulletRigidBodyNode, BulletGhostNode, BulletDebugNode
from panda3d.bullet import BulletPlaneShape, BulletBoxShape
from direct.showbase.ShowBase import ShowBase

class Game(ShowBase):
	def __init__(self):
		ShowBase.__init__(self)
		self.setFrameRateMeter(True)
		self.setBackgroundColor(0.1, 0.1, 0.8, 1)

		self.cam.setPos(0, -20, 4)
		self.cam.lookAt(0, 0, 2)

		# Input
		self.accept('escape', self.doExit)
		self.accept('r', self.doReset)

		# Task
		self.taskMgr.add(self.update, 'updateWorld')

		# Physics
		self.setup()

	def doExit(self):
		self.cleanup()
		sys.exit(1)

	def doReset(self):
		self.cleanup()
		self.setup()

	def update(self, task):
		dt = globalClock.getDt()
		mousePos = Vec2(0.0,0.0)
		if(self.mouseWatcherNode.hasMouse()):
			mousePos = self.mouseWatcherNode.getMouse()
			self.boxNP.setScale(mousePos.x+1.0)
			self.ghostBoxNP.setScale(mousePos.x+1.0)
		self.world.doPhysics(dt, 5, 1.0/180.0)

		return task.cont

	def cleanup(self):
		self.world.remove(self.groundNP.node())
		self.world.remove(self.boxNP.node())
		self.world.remove(self.ghostBoxNP.node())
		self.world = None

		self.debugNP = None
		self.groundNP = None
		self.boxNP = None
		self.ghostBoxNP = None

		self.worldNP.removeNode()

	def setup(self):
		self.worldNP = self.render.attachNewNode('World')

		# World
		self.debugNP = self.worldNP.attachNewNode(BulletDebugNode('Debug'))
		self.debugNP.show()
		self.debugNP.node().showWireframe(True)
		self.debugNP.node().showConstraints(True)
		self.debugNP.node().showBoundingBoxes(False)
		self.debugNP.node().showNormals(True)

		self.world = BulletWorld()
		self.world.setGravity(Vec3(0, 0, -9.81))
		self.world.setDebugNode(self.debugNP.node())

		# Ground (static)
		self.groundNP = self.worldNP.attachNewNode(BulletRigidBodyNode('Ground'))
		self.groundNP.node().addShape(BulletPlaneShape(Vec3(0, 0, 1), 1))
		self.groundNP.setPos(0, 0, -2)

		self.world.attachRigidBody(self.groundNP.node())

		# Box (dynamic)
		self.boxNP = self.worldNP.attachNewNode(BulletRigidBodyNode('Box'))
		self.boxNP.node().setMass(1.0)
		self.boxNP.setScale(2)
		self.boxNP.node().addShape(BulletBoxShape(Vec3(0.5, 0.5, 0.5)))
		self.boxNP.node().addShape(BulletBoxShape(Vec3(0.5, 0.5, 0.5)), TransformState.makePos(Vec3(1,0,0)) )
		self.boxNP.setPos(0, 0, 2)
		#self.boxNP.setScale(2, 1, 0.5)
		self.boxNP.node().setDeactivationEnabled(False)
		self.world.attach(self.boxNP.node())

		# ghost box
		self.ghostBoxNP = self.worldNP.attachNewNode(BulletGhostNode('ghostBox'))
		self.ghostBoxNP.setScale(1.5)
		self.ghostBoxNP.node().addShape(BulletBoxShape(Vec3(0.5, 0.5, 0.5)))
		self.ghostBoxNP.node().addShape(BulletBoxShape(Vec3(0.5, 0.5, 0.5)), TransformState.makePos(Vec3(1,0,0)) )
		self.ghostBoxNP.setPos(1, 0, 0.5)
		self.world.attach(self.ghostBoxNP.node())

game = Game()
game.run()
```

**Comment by PointSource-xx** [comment]
Still need to look into tests for single shape bodies and 'before' testcases that did not trigger the deadlock.

**Comment by PointSource-xx** [comment]
The scope of my PR has moved a little beyond just issue #689, other shape scaling problems have been addressed. I believe they are related enough to keep here. Is this OK?

**Comment by rdb** [comment]
As you wish, but note that the more changes are in this PR, the harder it is to review and merge it in time for 1.10.4.  I'd like this PR to just have the fixes that are critical for the bugfix release plus unit tests.

**Comment by PointSource-xx** [comment]
OK. I'll split it out and open another issue/pull request for the ghostbody scaling problem.

**Comment by PointSource-xx** [comment]
Ready to review.

**Comment by rdb** [comment]
Thank you for the detailed unit tests!

TBPH I'm a little nervous about applying this change to the 1.10.4 bugfix release; it seems that `do_transform_changed()` (depending on whether it's a rigid, ghost or soft body) does a whole bunch of things other than just set the local scale.

Furthermore, the change behaves differently from the existing behaviour when there is also a parent node that has a scale applied.  I'm not entirely sure which behaviour was intended, though.

**Comment by PointSource-xx** [comment]
> Furthermore, the change behaves differently from the existing behaviour when there is also a parent node that has a scale applied. I'm not entirely sure which behaviour was intended, though.

Thanks for picking that up! I should be using `get_net_transform()` in line with the existing behaviour. I will fix this and add a few more related tests.

I will also double-check for other side effects of not using `do_transform_changed()` for ghost, rigid & soft bodies.

**Comment by Moguri** [comment]
@PointSource-xx Are you still interested in pursuing this PR? If not, or if I don't here from you in two weeks, I intend to close this PR. It can always be re-opened.

**Comment by PointSource-xx** [comment]
Yes, I'll close this PR for now. Like you said, I can re-open when I have time to work on it again.

**Pull request closed without merging**
