### PR TITLE
Add hidden window mode

### PR DESCRIPTION
**Pull request by Moguri**
This PR implements an enumerated type for window modes. Support is added for the existing window mode properties as W_regular, W_fullscreen, W_undecorated. Fullscreen and undecorated support is handled by delegating to the existing properties. We can look into removing these to reclaim bits in the Specified bitfield and make the window modes truly mutually exclusive (right now some odd combinations can be set). However, for now I tried to keep the changes to a minimum to reduce the risk of bugs.

A new W_hidden WindowMode is implemented for X11 to hide a window from the window manager. Support for macOS and Windows is still TODO.

The changes were tested using a modified version of the asteroids sample.
[window_mode_test.zip](https://github.com/panda3d/panda3d/files/703519/window_mode_test.zip)

This PR is more of a request for review and feedback than a request for a merge at this point in time.

### CODE REVIEW

**Comment by Moguri** [comment]
Here is a completely untested patch for Windows support: https://hastebin.com/sopavezume.diff

**Comment by Moguri** [comment]
And here is a completely untested patch for macOS/Cocoa: https://hastebin.com/kasivubemi.diff

**Comment by rdb** [comment]
This is good.  I like this.

We should probably display a deprecation warning when people attempt to use `set_fullscreen()` and `set_undecorated()`.  Perhaps we should just drop the flags entirely but keep `set_fullscreen(true)`, etc. as a backward-compatible way to set the window mode.  Otherwise it will get a mess if there are two settings that do the same thing.  I don't mind breaking API compatibility as long as the only the most ubiquitous idioms still work.

I think there should probably be a `window-mode` config variable to set the default setting.

**Comment by Moguri** [comment]
I have rebased this branch to reflect changing the GraphicsWindows to use window_mode instead of fullscreen and undecorated. X11 is handled by this PR. I have win32 changes in a branch (window_mode_win), but they are still untested (have not even been compiled). Cocoa is still TODO.

**Comment by Moguri** [comment]
I have a window_modes_cocoa branch that compiles on build-osx, but is otherwise untested.

**Comment by Moguri** [comment]
I pulled all of the branches together and rebased them on top of master. I have pushed the branch to both this repo and my fork. I can create a new PR off of the panda3d/window_modes branch.

**Comment by Moguri** [comment]
This requires unit tests before being merge-ready. We need to test the new window_mode and make sure we didn't break the old API (get/set_undecorated(), get/set_fullscreen(), etc.).

Also, deprecation warnings should be added to the old API.

**Comment by Moguri** [comment]
I am tempted to drop this PR. I no longer need these changes anymore, and I am not sure if/when I will put in the energy to push this PR to completion. Thoughts?

**Comment by Moguri** [comment]
I am abandoning this PR. Someone else can feel free to pick it up again.

**Pull request closed without merging**
