### PR TITLE
general: Fully qualify header references into the std namespace

### PR DESCRIPTION
**Pull request by CFSworks**
This is phase 2 of #335.

It's a bit heavy to review. I suppose some combination of "look at random files" and "compile on all supported platforms" will give us good confidence nothing went wrong.

### CODE REVIEW

**Comment by rdb** [comment]
Thanks a ton!  I'll try building it on Windows and macOS.

**Comment by CFSworks** [comment]
I see the VRML issue; stand by for a fix.

**Comment by CFSworks** [comment]
@rdb Looks like dtoolbase.h pulling in Windows's minmax.h is causing min and max to be defined as macros, which is conflicting with std::min and std::max.

Should we be dropping that include?

**Comment by rdb** [comment]
It does not work on Windows, because the Windows headers define min and max
as macros.

I am told that defining NOMINMAX should fix that, but I can't get that to
work, even when defining it on the compiler command-line.

Alternatives are to omit the prefix for these to, or use them like:
(std::min)(x, y)

**Comment by rdb** [comment]
@CFSworks Ah, you beat me to it.  You're right, I didn't realise there was
an explicit include, that was part of the problem.

We will also need to add something like this to dtoolbase.h:

#ifdef _WIN32
#define NOMINMAX
#endif

...otherwise the Windows headers will still include it.

**Comment by CFSworks** [comment]
Speaking of `_WIN32`: All of the various platform macros are starting to get a little confusing. Is there documentation about various supported platforms (including multiple APIs on one platform, like Cygwin vs. MinGW vs. MSVC) and what One True Macro we're supposed to use to detect that platform (e.g. I see a lot of `defined(WIN32_VC) || defined(WIN64_VC)` but the latter implies the former), or is this worth another issue?

**Comment by CFSworks** [comment]
:+1: From me on Linux and Windows (w/ Clang). I've also done the "look at random files" test quite a bit and can't find anything else out of place.

**Comment by rdb** [comment]
There's still some errors in the DX9 code due to use of min/max with mismatched argument types.  I'll push this as soon as I've fixed those, assuming that's OK.  Thanks!

**Pull request closed without merging**
