### PR TITLE
FreezeTool: Create custom section for Panda's data in macOS deploy-stub, and some other fixes.

### LINKED ISSUE #871: FreezeTool: Generated Mach-O binary rejected by codesign
I've run into a few issues when messing around with macOS code signing using an executable generated with `build_apps`.

When doing a strict code sign (running `codesign` without `--no-strict`), the following is output:
```
./panda_app.app: main executable failed strict validation
```
According to an [Apple Technical Note](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG309), this usually happens when a mach-o file is post-processed incorrectly.

If one supplies the `--no-strict` flag, a binary created for the `macosx_10_6_x86_64` platform successfully signs, but crashes on launch.

<details><summary>Trace</summary>

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [399]

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	0x00007fff703f8c92 _platform_strlen + 18
1   libpython3.7.dylib            	0x000000010009c398 _PyUnicode_EqualToASCIIString + 72
2   libpython3.7.dylib            	0x000000010012e1e8 PyImport_ImportFrozenModuleObject + 72
3   libpython3.7.dylib            	0x000000010012e49b PyImport_ImportFrozenModule + 43
4   libpython3.7.dylib            	0x000000010013ad4d initimport + 45
5   libpython3.7.dylib            	0x000000010013d268 _Py_InitializeCore_impl + 1736
6   libpython3.7.dylib            	0x000000010013da22 _Py_InitializeCore + 402
7   libpython3.7.dylib            	0x000000010013da69 _Py_InitializeFromConfig + 57
8   libpython3.7.dylib            	0x000000010013dd6d Py_Initialize + 205
9                                 	0x0000000100002380 Py_FrozenMain + 384
10                                	0x0000000100002906 main + 838
11                                	0x00000001000021f4 start + 52

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000010028fc80  rbx: 0x00000001007ad0d0  rcx: 0x0866c3a089638054  rdx: 0x0866c3a089638054
  rdi: 0x0866c3a089638050  rsi: 0x0866c3a089638054  rbp: 0x00007ffeefbfd340  rsp: 0x00007ffeefbfd340
   r8: 0x0000000000000400   r9: 0x0000000101010600  r10: 0x00000001007ad110  r11: 0x56c90a409e2f0bdf
  r12: 0x00000000000000e5  r13: 0x0866c3a089638054  r14: 0x0000000100786d70  r15: 0x0000000101002a00
  rip: 0x00007fff703f8c92  rfl: 0x0000000000010206  cr2: 0x000000010009c350
  
Logical CPU:     2
Error Code:      0x00000000
Trap Number:     13
```
</details>

With a `macosx_10_9_x86_64` binary, `codesign` fails with
```
codesign_allocate: the __LINKEDIT segment does not cover the end of the file (can't be processed) in: [executable path]
```

### PR DESCRIPTION
**Pull request by treamology**
Wow, this took a while!

I had to investigate a bunch of ways to put game data into a Mach-O binary without just appending it to the end. Keeping the data at the end and pointing a segment at it did not work, since, apparently, __LINKEDIT needs to be the last segment (I only found this out by looking at the source code Apple thankfully published). So, the approach ended up being shifting a lot of the structures around and modifying offsets accordingly, which was daunting at first, but ended up being easier once I got more familiar with the Mach-O format.

This PR also contains some other fixes for issues that were preventing the final binary from being created correctly. Each fix is explained in the commit messages.

Fixes #871

### CODE REVIEW

**Comment by Moguri** [comment]
This looks good to me, but I do not know much about macOS binaries to commit on how "correct" this fix is. Would you mind rebasing this to pull in CI pipeline fixes? Also, do we want this against `master` or against `release/1.10.x`?

**Comment by rdb** [comment]
I'd overlooked this (perhaps I was waiting for the CI failures to be fixed).  This looks good to me, thanks for working on this!

I think this is probably a change for master due to the inherent risk involved with these kinds of changes, unless it solves a critical bug that can't be worked around.

**Comment by treamology** [comment]
I'm fairly certain these test fails were caused outdated CI scripts, can someone with access trigger a re-run?

**Comment by rdb** [comment]
The CI scripts are in the repo, so you'll need to rebase or merge from master and it'll rebuild with the latest scripts.

**Comment by treamology** [comment]
Huh, for some reason I thought it used what was in the current master unless they were specifically edited in a commit.

**Comment by rdb** [comment]
Rebased to master as 46ae5a52d3add3691050021397babb929e2c7fdd 23041ec069d4025a949285e7365146a6a41b01de 0f3948005f5f18ce6272e7cac1fe70f385fe705b

**Pull request closed without merging**
